### ISSUE TITLE
Labelled/Unlabelled Split

### ISSUE THREAD

**Issue by Giuseppe5** [FBLADL/ACPL#1]
Hello,
Thank you for providing the code for your project!
I would like to know if it is possible to release also the files associated to the other splits you present in your dataset (i.e., 5%, 10%, 15%, and 20%)?
Also, I while looking at the train_val_list_2_1.txt file, I noticed that 9 images are actually duplicated. Is there a reason behind that?

Many thanks!

**Comment by FBLADL** [comment]
Hi,
I have upload the script I used for generating the data split. You can use it for generating different ratio. 
The duplicated samples are caused by the dataset is multi-labelled and we are sampled by class. They are handled in the script.

Cheers
