### ISSUE TITLE
Code error in dataloader_cx14.py

### ISSUE THREAD

**Issue by Xglbrilliant** [FBLADL/ACPL#3]
Thanks for your great work! But recently, when I reproduced, I found that the code on lines 13 and 168 in dataloader_cx14.py reported an error. I checked the utils.py file and found that the above method does not exist in the file. Can you please explain?
![image](https://user-images.githubusercontent.com/95476150/199659515-652b1ea7-d544-44cd-a4ab-397ab62bc9d4.png)
![image](https://user-images.githubusercontent.com/95476150/199659466-7cc059c4-63c5-4105-a738-23f644f172fd.png)

**Comment by FBLADL** [comment]
Hi, dataloder_cx14.py is not used. It is an old version. The correct dataloader is dataloder_semi.py, which is used [here](https://github.com/FBLADL/ACPL/blob/20cb6b069d2c75eaa675aaa1d915aa1d1acd25fd/pl_trainer.py#L17) . I guess it is creating confusion, I am going to delete that.

**Comment by FBLADL** [comment]
Done, closing the issue.
