### ISSUE TITLE
Confusion in Datasets Preparation

### ISSUE THREAD

**Issue by you-see-see** [FBLADL/ACPL#4]
Hello，may i ask what is the mearning of  “Move semi_sample.py to the dataset folder”, i just moved it to my dataset folder, but i didn’t find anywhere used it in the code?

**Comment by FBLADL** [comment]
Hi, it is a script for creating semi-supervised experiment setup and it should be run separately. Just change [ratio](https://github.com/FBLADL/ACPL/blob/41c096b60c44c8a5467702bf8d0f9763ee681dbf/semi_sample.py#L49) and [naming](https://github.com/FBLADL/ACPL/blob/41c096b60c44c8a5467702bf8d0f9763ee681dbf/semi_sample.py#L53) when creating different labeled ratios.

**Comment by TqXue** [comment]
Thanks for your reply! I understand!
